version: '3.8'
services:
  web:
    build:
      context: ./src/
      dockerfile: Dockerfile
    command: gunicorn bomberos.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_volume:/home/app/web/staticfiles/
      - type: bind
        source: ./db.sqlite3
        target: /home/app/web/db.sqlite3
    restart: always
  nginx:
    build: ./nginx/
    volumes:
      - static_volume:/home/app/web/staticfiles/
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
volumes:
  static_volume:
